# Generated by Django 5.2.7 on 2025-10-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id_plantel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=200)),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('modelo', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('no_serie', models.CharField(max_length=200)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.departamento')),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=200)),
                ('nota', models.CharField(max_length=200)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.departamento')),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='registro_producto',
            fields=[
                ('id_rp', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=140)),
                ('correo', models.TextField()),
                ('contraseña', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=200)),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.plantel')),
            ],
        ),
    ]
